services:
  db:
    image: mariadb:10.6
    container_name: mina-glamour-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mina_root_password
      - MYSQL_DATABASE=mina_glamour_wp
      - MYSQL_USER=mina_user
      - MYSQL_PASSWORD=mina_password
    networks:
      - mina-net

  wordpress:
    image: wordpress:latest
    container_name: mina-glamour-wp
    ports:
      - "8080:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=mina_user
      - WORDPRESS_DB_PASSWORD=mina_password
      - WORDPRESS_DB_NAME=mina_glamour_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - mina-net
    depends_on:
      - db

networks:
  mina-net:
    driver: bridge

volumes:
  db_data:
